import type { Word } from "./types";

type Seed = Pick<
  Word,
  "en" | "zh" | "phonetic" | "pos" | "exampleEn" | "exampleZh" | "tags"
>;

const SEED: Seed[] = [
  {
    en: "opportunity",
    zh: "機會",
    phonetic: "/ˌɒpəˈtjuːnəti/",
    pos: "n. 名詞",
    exampleEn: "This internship is a rare opportunity.",
    exampleZh: "這次實習是難得的機會。",
    tags: ["核心"],
  },
  {
    en: "however",
    zh: "然而、不過",
    phonetic: "/haʊˈevə/",
    pos: "adv. 副詞",
    exampleEn: "The plan is solid; however, we need more time.",
    exampleZh: "計畫很穩妥；然而，我們需要更多時間。",
    tags: ["核心"],
  },
  {
    en: "recommend",
    zh: "推薦",
    phonetic: "/ˌrekəˈmend/",
    pos: "v. 動詞",
    exampleEn: "I recommend starting with ten words a day.",
    exampleZh: "我建議從每天十個單字開始。",
    tags: ["日常"],
  },
  {
    en: "comfortable",
    zh: "舒適的",
    phonetic: "/ˈkʌmftəbl/",
    pos: "adj. 形容詞",
    exampleEn: "This chair is more comfortable than it looks.",
    exampleZh: "這張椅子比看起來更舒適。",
    tags: ["日常"],
  },
  {
    en: "environment",
    zh: "環境",
    phonetic: "/ɪnˈvaɪrənmənt/",
    pos: "n. 名詞",
    exampleEn: "A quiet environment helps me focus.",
    exampleZh: "安靜的環境幫助我專心。",
    tags: ["核心"],
  },
  {
    en: "confident",
    zh: "有自信的",
    phonetic: "/ˈkɒnfɪdənt/",
    pos: "adj. 形容詞",
    exampleEn: "She felt more confident after the rehearsal.",
    exampleZh: "彩排之後，她變得更有自信。",
    tags: ["核心"],
  },
  {
    en: "although",
    zh: "雖然",
    phonetic: "/ɔːlˈðəʊ/",
    pos: "conj. 連接詞",
    exampleEn: "Although it was raining, we kept walking.",
    exampleZh: "雖然在下雨，我們還是繼續走。",
    tags: ["核心"],
  },
  {
    en: "necessary",
    zh: "必要的",
    phonetic: "/ˈnesəsəri/",
    pos: "adj. 形容詞",
    exampleEn: "A passport is necessary for this trip.",
    exampleZh: "這趟旅行必須帶護照。",
    tags: ["核心"],
  },
  {
    en: "experience",
    zh: "經驗；經歷",
    phonetic: "/ɪkˈspɪəriəns/",
    pos: "n. 名詞／v. 動詞",
    exampleEn: "She has years of teaching experience.",
    exampleZh: "她有多年的教學經驗。",
    tags: ["核心"],
  },
  {
    en: "schedule",
    zh: "行程、時間表",
    phonetic: "/ˈʃedjuːl/",
    pos: "n. 名詞／v. 動詞",
    exampleEn: "Let me check my schedule for Friday.",
    exampleZh: "我看一下星期五的行程。",
    tags: ["日常"],
  },
  {
    en: "appreciate",
    zh: "感謝；欣賞",
    phonetic: "/əˈpriːʃieɪt/",
    pos: "v. 動詞",
    exampleEn: "I appreciate your help with the notes.",
    exampleZh: "謝謝你幫忙整理筆記。",
    tags: ["日常"],
  },
  {
    en: "available",
    zh: "有空的；可使用的",
    phonetic: "/əˈveɪləbl/",
    pos: "adj. 形容詞",
    exampleEn: "Are you available after three?",
    exampleZh: "你三點以後有空嗎？",
    tags: ["日常"],
  },
  {
    en: "look forward to",
    zh: "期待",
    phonetic: "/lʊk ˈfɔːwəd tuː/",
    pos: "phr. 片語",
    exampleEn: "I look forward to seeing you next week.",
    exampleZh: "我很期待下週見到你。",
    tags: ["片語"],
  },
  {
    en: "make sense",
    zh: "合理、說得通",
    phonetic: "/meɪk sens/",
    pos: "phr. 片語",
    exampleEn: "Your explanation finally makes sense.",
    exampleZh: "你的解釋終於說得通了。",
    tags: ["片語"],
  },
  {
    en: "in charge of",
    zh: "負責",
    phonetic: "/ɪn tʃɑːdʒ ɒv/",
    pos: "phr. 片語",
    exampleEn: "Who is in charge of the guest list?",
    exampleZh: "誰負責賓客名單？",
    tags: ["片語"],
  },
  {
    en: "deadline",
    zh: "截止日期",
    phonetic: "/ˈdedlaɪn/",
    pos: "n. 名詞",
    exampleEn: "The deadline is Friday at noon.",
    exampleZh: "截止日期是星期五中午。",
    tags: ["日常"],
  },
  {
    en: "improve",
    zh: "改善、進步",
    phonetic: "/ɪmˈpruːv/",
    pos: "v. 動詞",
    exampleEn: "Daily review will improve your memory.",
    exampleZh: "每天複習會改善你的記憶。",
    tags: ["核心"],
  },
  {
    en: "responsible",
    zh: "負責的",
    phonetic: "/rɪˈspɒnsəbl/",
    pos: "adj. 形容詞",
    exampleEn: "He is responsible for locking up.",
    exampleZh: "他負責關門。",
    tags: ["核心"],
  },
];

export const ZH_DISTRACTORS = [
  "天氣",
  "會議",
  "勇氣",
  "桌子",
  "決定",
  "風景",
  "習慣",
  "意見",
  "車站",
  "鄰居",
  "成績",
  "早餐",
  "週末",
  "行李",
  "合約",
  "耐心",
];

export const EN_DISTRACTORS = [
  "weather",
  "meeting",
  "courage",
  "table",
  "decision",
  "scenery",
  "habit",
  "opinion",
  "station",
  "neighbor",
  "grade",
  "breakfast",
  "weekend",
  "luggage",
  "contract",
  "patience",
];

export function buildSeedWords(now = Date.now()): Word[] {
  return SEED.map((item) => ({
    id: `seed-${item.en.replace(/\s+/g, "-")}`,
    ...item,
    note: "",
    starred: false,
    ease: 0,
    intervalDays: 0,
    nextReviewAt: 0,
    reviewCount: 0,
    correctCount: 0,
    wrongCount: 0,
    createdAt: now,
    updatedAt: now,
    source: "seed" as const,
  }));
}
